language: csharp
mono: none
dotnet: 2.1.3

install:
  - dotnet restore ImgAzyobuziNet.sln

script:
  - dotnet build Analyzers/ImgAzyobuziNet.Analyzers.Core/ImgAzyobuziNet.Analyzers.Core.csproj
  - dotnet test TestProjects/ImgAzyobuziNet.Core.Test/ImgAzyobuziNet.Core.Test.csproj --filter TestCategory=Static
