trigger:
  branches:
    include: ['*']
    exclude: [v1, v2, oldv3]
  paths:
    include: ['*']
    exclude:
      - README.md
      - docs/*
      - ItemTemplates/*

pr:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-16.04

variables:
  DotNetCoreSdkVersion: '2.2.103'
  BuildConfiguration: Release

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: $(DotNetCoreSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build analyzers
    inputs:
      command: build
      projects: Analyzers/**/*.csproj
  - task: DotNetCoreCLI@2
    displayName: Build ImgAzyobuziNet.Core
    inputs:
      command: build
      projects: ImgAzyobuziNet.Core/ImgAzyobuziNet.Core.csproj
  - task: DotNetCoreCLI@2
    displayName: Run tests
    inputs:
      command: test
      projects: TestProjects/ImgAzyobuziNet.Core.Test/ImgAzyobuziNet.Core.Test.csproj
      arguments: --filter TestCategory=Static
  - task: DotNetCoreCLI@2
    displayName: Build Azure Functions project
    inputs:
      command: publish
      publishWebProjects: false
      projects: ImgAzyobuziNet.AzureFunctions/ImgAzyobuziNet.AzureFunctions.csproj
      arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1
